version: '2'

services:
  pgdb:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    # TODO: Substitute it with gunicorn command
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/web/
      - ./media:/web/media/
      - ./staticfiles:/web/staticfiles/
    ports:
      - 8000:8000
    depends_on:
      - pgdb
    links:
      - pgdb
