from django.conf.urls import url
from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.index,
        name='index'
    ),
    url(
        regex=r'^mascotas/$',
        view=views.pets,
        name='pets'
    ),
    url(
        regex=r'^mascotas/(?P<pet_id>[0-9]+)/(?P<slug>[\w-]+)/$',
        view=views.pet_detail,
        name='pet_detail'
    ),
    url(
        regex=r'^mascotas/(?P<pet_id>[0-9]+)/(?P<slug>[\w-]+)/adoptar/$',
        view=views.new_adoption_request,
        name='new_adoption_request'
    ),
    url(
        regex=r'^mascotas/(?P<pet_id>[0-9]+)/(?P<slug>[\w-]+)/editar/$',
        view=views.edit_pet,
        name='edit_pet'
    ),
    url(
        regex=r'^mascotas/(?P<pet_id>[0-9]+)/(?P<slug>[\w-]+)/borrar/$',
        view=views.delete_pet,
        name='delete_pet'
    ),
    url(
        regex=r'^mascotas/nueva/$',
        view=views.new_pet,
        name='new_pet'
    ),
    url(
        regex=r'^mensajes/$',
        view=views.messages,
        name='messages'
    ),
    url(
        regex=r'^buscar/$',
        view=views.search,
        name='search'
    ),
    url(
        regex=r'^primera-visita/$',
        view=views.first_login,
        name='first_login'
    ),
    url(
        regex=r'^asociaciones/$',
        view=views.organisations,
        name='organisations'
    ),
    url(
        regex=r'^crear-asociacion/$',
        view=views.create_organisation,
        name='create_organisation'
    ),
    url(
        regex=r'^guardar-informacion/$',
        view=views.create_user_info,
        name='create_user_info'
    ),
    url(
        regex=r'^mi-perfil/$',
        view=views.my_profile,
        name='my_profile'
    )
]
